server:
  port: 8300
spring:
  application:
    name: MemberService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

# http://127.0.0.1/swagger-ui.html
swagger:
  base-package: com.aaron.member.impl
  title: MemberService
  description: MemberService
  version: 1.1
  terms-of-service-url: www.aaron.com
  contact:
    name: lfl
    email: 361647454@qq.com